Update numba version
shap/shap pull request #2573
Opened 2022-06-01 18:41 UTC by bchen1116

With `shap==0.40.0`, various versions of `numba` installations give errors during or after installation:

`numba==0.1` gives this when trying to import:
<img width="1025" alt="Pasted Graphic 12" src="https://user-images.githubusercontent.com/22552445/171477784-03db19a5-0645-4584-9ac0-5c655e59ad2b.png">

`numba<0.45.0` gives this when trying to install:
<img width="1715" alt="Pasted Graphic 13" src="https://user-images.githubusercontent.com/22552445/171477842-9cbda59f-d394-410c-a7b3-ae1dca7e80f3.png">

`numba<=0.48.0` has a successful installation and but failed import:
<img width="1379" alt="Pasted Graphic 14" src="https://user-images.githubusercontent.com/22552445/171477939-8e23f9d0-de8c-4c2c-9d0f-32b539cccf8f.png">
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/22552445/171478037-692f0e85-476b-48b7-8137-b24f954d1488.png">

`numba>=0.49.0` works successfully!
<img width="1534" alt="image" src="https://user-images.githubusercontent.com/22552445/171495810-efe5c2e0-7eed-45c0-be21-662c740b2cea.png">

Updating the `numba` allowed versions to avoid these failures
These were all run with py3.8 in a fresh environment with `shap==0.40.0`

2022-06-02 16:15 UTC, imatiach-msft commented
@bchen1116 numba and numpy have to be updated in sync together, so I think this is a weird change.  For newer versions of numpy, newer versions of numba need to be used.  Similarly, for older versions of numpy, older versions of numba need to be used.  I think pinning it like this (and also pinning numpy) is the wrong way, especially with such a high pin, it will mean that projects that depend on older numpy won't be able to use the latest shap.  Instead, upstream projects that use shap should pin numpy and numba together to compatible versions, and shap should try to minimize pinning as much as possible.

2022-06-02 16:21 UTC, imatiach-msft commented
Also, notice how in your successful install you have numpy 1.22.4 installed, but actually in the shap setup.py numpy is pinned to <1.22!  So now you are changing shap to pin to two incompatible ranges of versions of numpy and numba.  I think the better fix is to remove both numpy and numba pins in shap, and the person who installs shap need to install the right compatible versions, otherwise with such incompatible versions specified this will turn in [dependency hell](https://en.wikipedia.org/wiki/Dependency_hell).

![image](https://user-images.githubusercontent.com/24683184/171676930-817214f9-3030-49be-aea7-a26f11268141.png)

2022-06-02 16:22 UTC, imatiach-msft requested changes
the pinned numba and numpy versions are incompatible now, numpy<1.22 is incompatible with numba>=0.49.0

2022-06-03 14:12 UTC, bchen1116 commented
@imatiach-msft I see what you mean, thanks for the response and input. Closing this out

2022-06-03 14:12 UTC, closed without merging