Replaced Boston dataset with California in Catboost tutorial
shap/shap pull request #3214
Opened 2023-08-23 12:49 UTC by owenlamont

## Overview

Description of the changes proposed in this pull request:

This is another step towards completing [issue 2322](https://github.com/shap/shap/issues/2322).

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2023-08-26 08:55 UTC, thatlittleboy commented
Thanks @owenlamont for the contribution.

It's a little hard to review notebooks on GH, I'll use images to get my point across:

![image](https://github.com/shap/shap/assets/30731072/d0d76b0b-eeba-4faa-ad9e-015a9ab5beaf)

* red box: Typo, should be `AveRooms`.
* pink box: The coloring is by `MedInc`, not `RAD`.

![image](https://github.com/shap/shap/assets/30731072/5b0a0c9e-bf1f-4609-a081-82eea23556cf)

* there isn't an LSTAT feature in California, you can change it to MedInc.

2023-08-26 08:55 UTC, thatlittleboy requested changes
see comment above.

2023-08-26 10:51 UTC, owenlamont commented
Cheers, yeah I should've been aware the features would be different, I'll get onto those updates.

2023-08-26 11:39 UTC, owenlamont commented
I've tweaked the text, I'm struggling a little to give a reasonable interpretation of the dependence plot description, would welcome feedback on that (maybe there's a better feature I should have chosen for the dependence plot other than AveRooms that would have given an easier to interpret plot).

![image](https://github.com/shap/shap/assets/12672027/f159a329-4086-4c84-9b6f-721260c988d5)

2023-08-27 17:46 UTC, thatlittleboy commented
@owenlamont I went round all the variables and didn't really find any variables' dependence plot to be particularly illustrative / easy to interpret.

What do you think about this instead? It's the best I could come up with.

![image](https://github.com/shap/shap/assets/30731072/865d843a-f76d-4b6f-a51d-583b81bd3894)

I'm seeing that:
* at lower MedInc (let's say <=4), the HouseAge doesn't have a strong impact on the house prices (or at least, the dependence relationship isn't that clear tome)
* at higher MedInc, older houses tend to have higher prices (if we squint a little, we can generally see that the red dots are higher than the blue dots, for the same MedInc).

2023-09-09 12:50 UTC, owenlamont commented
Thanks for the feedback @thatlittleboy - I've used your example and tweaked your phrasing a little for the description. I hope that looks okay:

![image](https://github.com/shap/shap/assets/12672027/8e617a8a-7f81-426d-9fa4-92e50d30ddbc)

I also noticed the old Boston House Price example is used on the main README too... guess at some point that should be changed. I think we might want an entirely different dataset we can tell a nice story with using SHAP for that though.

2023-09-13 04:01 UTC, dsgibbons commented
> I also noticed the old Boston House Price example is used on the main README too... guess at some point that should be changed. I think we might want an entirely different dataset we can tell a nice story with using SHAP for that though.

@owenlamont this has been fixed by #3200. Happy for another dataset to be used if it tells a more compelling story.

2023-09-17 11:01 UTC, owenlamont commented
Yeah... I'm sure there must be a better dataset for this example. I'm afraid I'm a bit time poor and have some other priorities so I don't think I'll go looking for it myself but happy to try and keep contributing in small ways.

2023-10-01 06:25 UTC, thatlittleboy approved these changes
Thanks @owenlamont for the contribution, Sorry it took so long to get back to you. I took the liberty to clean up a couple more things, like using the new `plots` api (e.g. `shap.plots.force` instead of `shap.force_plot`) where possible.


![clockwork-thumbsup](https://media.giphy.com/media/8xSnw21AM7OQo/giphy-downsized.gif)

2023-10-01 06:29 UTC, merged

2023-10-14 11:45 UTC, owenlamont commented
Thanks for finishing it off @thatlittleboy !