ENH replave np.linalg.inv and pinv by np.linalg.solve
shap/shap pull request #3271
Opened 2023-09-22 13:57 UTC by lorentzenchr

## Overview

Closes #3270.

Description of the changes proposed in this pull request:
The use of `np.linalg.inv` to solve linear equations or least squares problem is unstable and inefficient (memory- and cpu-wise). This PR replaces those by numerically much more stable and efficient linear algebra routines.

## Checklist

- [ ] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2023-10-02 19:18 UTC, lorentzenchr commented
@thatlittleboy Thanks or having a look.
Do you want the codecov fixed? It could be difficult to trigger those lines and they also were not covered before.

2023-10-03 01:28 UTC, thatlittleboy commented
@lorentzenchr No need, as long as you cover the proposed changes, I think it's fine

2023-10-03 16:20 UTC, lorentzenchr commented
> @lorentzenchr No need, as long as you cover the proposed changes, I think it's fine

It should be covered by existing tests in `tests/explainers/test_kernel.py`.

2023-10-15 15:22 UTC, thatlittleboy requested changes
Hi @lorentzenchr sorry this took so long to get back:

Couple of things apart from the specific review comments:

1. I'll prefer if we don't touch the shap paper notebooks, those are in the shap repository mostly as a record, unless @slundberg expresses desire to update them.
2. I don't think your "Simple Kernel SHAP" notebook runs properly, please double check. Thanks!

2023-10-15 15:22 UTC, thatlittleboy commented on shap/explainers/_kernel.py
> +            w = np.linalg.solve(X.T @ WX, WX.T @ eyAdj2)
Use `y` instead of `eyAdj2` here?

2023-10-15 15:22 UTC, thatlittleboy commented on shap/explainers/_kernel.py
> +            w = np.linalg.lstsq(sqrt_W[:, None] * etmp, sqrt_W * y)
1. Use `X` instead of `etmp` here?
2. Shouldn't this be

```python
w = np.linalg.lstsq(...)[0]
```

?

2023-10-15 15:22 UTC, thatlittleboy commented on shap/explainers/_kernel.py
> +            # w = np.dot(tmp2, np.dot(np.transpose(WX), eyAdj2))
Use `y` instead of `eyAdj2` here?

2023-10-15 15:22 UTC, thatlittleboy commented on notebooks/tabular_examples/model_agnostic/Simple Kernel SHAP.ipynb
> +    "    return result.x\n",
Shouldn't this be `result[0]` ? Seems like the result is a normal tuple, not a namedTuple or anything with an attribute access.

Please also ensure that you "Restart notebook and run all cells" so the output cells are also refreshed.

2023-10-18 19:04 UTC, lorentzenchr commented
@thatlittleboy Thanks for the review. I addressed all 3 points and review comments.

2023-10-20 16:19 UTC, thatlittleboy approved these changes
thanks!

![dog-hopping-low-five](https://media.giphy.com/media/u8tbFJtOE7eQlq1Eii/giphy.gif)

2023-10-20 16:37 UTC, merged

2023-10-20 17:41 UTC, jjerphan commented
Thank you, Christian.