Add causalml support
shap/shap pull request #3273
Opened 2023-09-23 18:54 UTC by alexander-pv

## Overview

This PR is reopened https://github.com/shap/shap/pull/2654

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2023-09-26 13:54 UTC, connortann commented
The tests are failing due to an unrelated HuggingFace error: apologies. We'll get that sorted asap (on #3286), and then we can get this PR passing.

2023-09-27 01:49 UTC, connortann commented
This PR has quite a large diff, as there are many unrelated style changes alongside the functional changes. Please would you remove the style changes, leaving just the functional changes?

On a related note, we plan to introduce autoformatting with python black soon to

2023-09-28 21:35 UTC, alexander-pv commented
Apologies for style change. I will remove it.

2023-10-01 08:24 UTC, thatlittleboy commented
Hi @alexander-pv , do you think you could also add in some tests to `test_tree.py` (just a simple function or two to demonstrate that the proposed changes here work as expected?)

Thanks!

2023-12-04 11:47 UTC, connortann commented
I'll add the "stale" label for now as there hasn't been recent activity. Please feel free to comment if you're still interested in the PR and are happy to work on adding a minimal unit test.

2023-12-08 23:34 UTC, alexander-pv commented
Hi, @connortann!  I added several test to check if shap works as intended with causalml trees.

2023-12-08 23:47 UTC, alexander-pv commented
About current scikit-learn building issue in recent tests: https://github.com/scikit-learn/scikit-learn/issues/26858

2023-12-21 13:29 UTC, connortann commented
Apologies that we haven't had time to look further at this PR, as many maintainers are away over the Christmas period. Thanks again for the PR - I hope to get to this early in the new year.

2024-04-21 11:25 UTC, alexander-pv commented
Hi, @connortann! I updated the PR resolving a couple of conflicts. Tests work as expected on my computer.
So, awaiting feedback from label can be removed now. I will be glad to contribute if you think anything else is needed for this PR!

Thanks!

2024-05-10 17:16 UTC, jeongyoonlee commented
Hi, @connortann. Can you take a look at this PR? This has been a long-standing issue (e.g., uber/causalml#265, uber/causalml#527, uber/causalml#615, uber/causalml#727, uber/causalml#735) for the `causalml` package, and we hope to resolve it soon.

Your support will be greatly appreciated.

2024-09-13 16:05 UTC, jeongyoonlee commented
@alexander-pv, can you look into the test failure?

2025-03-16 08:48 UTC, CloseChoice requested changes

2025-03-16 08:48 UTC, CloseChoice commented on tests/explainers/test_tree.py
> +class TestExplainerCausalML:
we typically don't use classes in shap tests, would be great if you could refactor to use pytest.fixtures instead.

Also 
```python
        from causalml.dataset import synthetic_data
        from causalml.inference.tree import CausalTreeRegressor

        X, y, treatment = self.prepare_data(synthetic_data)
 ```       
        could be handled in those. Pls also consider the usage of `pytest.importorskip` so that tests pass even if causalml is not installed.

2025-03-16 08:49 UTC, CloseChoice commented
Thanks for the PR and sorry that this took so, so long. Will try to respond in a timely manner, pls feel free to ping me whenever you have questions or want another review.

2025-03-16 16:13 UTC, alexander-pv commented
> Thanks for the PR and sorry that this took so, so long. Will try to respond in a timely manner, pls feel free to ping me whenever you have questions or want another review.

Ok, thanks!

2025-03-22 23:13 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +class TestExplainerCausalML:
Hi, @CloseChoice :wave: , can you review my latest changes, please?
Thanks

2025-03-23 06:45 UTC, CloseChoice requested changes

2025-03-23 06:45 UTC, CloseChoice commented on shap/explainers/_tree.py
> +                "causalml.inference.tree.CausalRandomForestRegressor",
is it possible that we add an info that causalml support is experimental using the logging module?

2025-03-23 06:45 UTC, CloseChoice commented on tests/explainers/test_tree.py
> +    shap_values_raw: list[np.ndarray] = ctree_explainer.shap_values(X)
could you pls check the `__call__` interface as well?

2025-03-23 06:45 UTC, CloseChoice commented on tests/explainers/test_tree.py
> +    shap_values: np.ndarray = np.stack(shap_values_raw, axis=-1)
why is the output a list? For trees in general we moved to the shape
`[num_observations, ...features, n_classes]` for classifications and
`[num_observations, ...features, n_outputs]` for regression. Could you pls elaborate what each of these outputs mean? I couldn't find it at a quick glance at the causalml docs

2025-03-23 11:58 UTC, alexander-pv commented on shap/explainers/_tree.py
> +                "causalml.inference.tree.CausalRandomForestRegressor",
Definitely :+1: TreeExplainer class constructor seems to be the best place for it. Is it OK to use warnings module as in the other functions of this module?

2025-03-23 11:58 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +    shap_values_raw: list[np.ndarray] = ctree_explainer.shap_values(X)
Ok :+1:

2025-03-23 12:02 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +    shap_values: np.ndarray = np.stack(shap_values_raw, axis=-1)
Thank you for the comment! Apologies, that's my mistake. It is in fact a numpy array. I'll fix it and add detailed explanation of the output.

2025-03-23 13:18 UTC, CloseChoice commented on shap/explainers/_tree.py
> +                "causalml.inference.tree.CausalRandomForestRegressor",
yes, that's fine

2025-03-23 13:21 UTC, CloseChoice commented on tests/explainers/test_tree.py
> +    shap_values: np.ndarray = np.stack(shap_values_raw, axis=-1)
First of all, I would never blame anyone here for any code contributed to shap (except for things that harm the project intentionally of course). Secondly we did the breaking change mid 2024, when this PR was already created and we just didn't check that due to capacity shortcomings and, I have to say, if anyone did a mistake here I would blame it on us, the maintainers. 

So long story short: thanks a lot for your contribution, we highly appreciate it.

2025-03-23 15:58 UTC, alexander-pv commented on shap/explainers/_tree.py
> +                "causalml.inference.tree.CausalRandomForestRegressor",
Added `_safe_check_tree_instance_experimental` for that purpose

2025-03-23 16:00 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +    shap_values_raw: list[np.ndarray] = ctree_explainer.shap_values(X)
Added `__call__` output check ( `Explanation` class)

2025-03-23 16:06 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +    shap_values: np.ndarray = np.stack(shap_values_raw, axis=-1)
I think everything is correct now. Please, add comments if you notice something else during the review.
Thanks again for a quick feedback! :handshake:

2025-03-23 16:13 UTC, alexander-pv commented on shap/utils/_warnings.py
> +class ExperimentalWarning(Warning):
Decided to suggest custom warnings similar to existing `_exceptions.py`. Of course, it is not very consistent to add a new module in this commit, but this class can clearly be reused during the initial integration of new model and I feel blue placing it inside `_tree.py` :sweat_smile: .
Let me know if it is better to avoid it at this time.

2025-03-23 17:41 UTC, CloseChoice requested changes

2025-03-23 17:41 UTC, CloseChoice commented on shap/explainers/_tree.py
> +                f"The {library} support is verified for the following versions: {experimental.get(library)}.",
Can we make clear that we do not commit ourselves to supporting this long term
```suggestion
                f"The {library} support is verified for the following versions: {experimental.get(library)}. "
                 f"As experimental functionality, this integration may be removed or significantly changed in future releases without following semantic versioning. Use in production systems at your own risk.",
```

2025-03-23 17:41 UTC, CloseChoice commented on shap/explainers/_tree.py
> +            self,
is there a particular reason for the formatting changes? I would to limit changes to either formatting or adding functionality, and not mix both into one PR.

2025-03-23 17:41 UTC, CloseChoice commented on shap/utils/_warnings.py
> +class ExperimentalWarning(Warning):
I think that's a good idea, let's go with it.

2025-03-23 17:41 UTC, CloseChoice commented on tests/explainers/test_tree.py
> +        individual_effects = y_outcomes[:, 1] - y_outcomes[:, 0]
If I understand it correctly the difference between the treatment effect and the non-treatment effect is the uplift, correct? This is exactly what we're calculating here, therefore it must match `preds`

2025-03-23 17:42 UTC, CloseChoice commented
@alexander-pv I think we're almost through. Could you pls just remove the formatting changes (or explain why we need them) and add the comment regarding future support in the warning and we're good to merge.

2025-03-23 17:49 UTC, alexander-pv commented on tests/explainers/test_tree.py
> +        individual_effects = y_outcomes[:, 1] - y_outcomes[:, 0]
Yes, that's correct

2025-03-23 18:17 UTC, alexander-pv commented on shap/explainers/_tree.py
> +            self,
Hmm, I didn't change formatting although it is showed in the merge commit https://github.com/shap/shap/pull/3273/commits/cc326cc3ecb9d655443af66ca69c0b1ab5701066. Anyway the latest diff shows that nothing changed.

2025-03-23 18:19 UTC, alexander-pv commented
> @alexander-pv I think we're almost through. Could you pls just remove the formatting changes (or explain why we need them) and add the comment regarding future support in the warning and we're good to merge.

Done. Answered in the comments above.

2025-03-23 19:01 UTC, CloseChoice approved these changes
Very nice work. Thanks for the effort and patience; this has been a long time coming.

2025-03-23 19:09 UTC, CloseChoice commented
@alexander-pv : I created a branch based on yours and fixed the pre-commit issues: https://github.com/shap/shap/tree/feature/causalml_trees. Pls merge that one in and then we'll merge it

2025-03-23 19:49 UTC, alexander-pv commented
> @alexander-pv : I created a branch based on yours and fixed the pre-commit issues: https://github.com/shap/shap/tree/feature/causalml_trees. Pls merge that one in and then we'll merge once the tests pass

Merged :ok_hand:

2025-03-23 20:16 UTC, merged