clean up league of legends notebook
shap/shap pull request #3275
Opened 2023-09-24 15:57 UTC by CloseChoice

## Overview

works towards #3036.

Description of the changes proposed in this pull request:
Fix the League of Legends Win Prediction with XGBoost notebook

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] ~Unit tests added (if fixing a bug or adding a new feature)~

Note: Am not quite sure if I added the precommit hook correctly, it seems like the notebook is not tested.

2023-09-26 23:49 UTC, connortann commented on .pre-commit-config.yaml
> +                notebooks/tabular_examples/tree_based_models/League of Legends Win Prediction with XGBoost.ipynb|
This list is a regular expression, so I don't think the spaces will match correctly here. You could use a shorter pattern instead:

```suggestion
                notebooks/tabular_examples/tree_based_models/League.*.ipynb|
```

This is just a temporary measure whilst some notebooks are not yet clean.

2023-09-26 23:53 UTC, connortann commented
Thanks for the PR, it would be great to clean up more of these notebooks.

As per my other comment on your other PR, may I suggest:
1. Fix the warning messages, which might be a case of just updating your 3rd party dependencies, and
2. Keep the cell execution numbers

2023-10-01 08:27 UTC, thatlittleboy commented
As mentioned in your other PR, this is potentially duplicated in #3234 (which was recently approved, I'll leave Connor to merge that in).
As usual, if there are other changes you would like to propose on top of that (linting + formatting), feel free to rebase on top of master once #3234 is merged in. Thanks!

2023-10-03 08:24 UTC, connortann commented
The code cells in this PR have been cleaned up nicely, so I'd like to get this version merged. However, I noticed there seems to be something off with the SHAP values.

The Shap plots look rather different in this new version. Here are some screenshots, with the existing docs on the left and this PR on the right-hand side:

![image](https://github.com/shap/shap/assets/71127464/122fe54b-3104-4c8a-b7e8-617af56cb61a)

![image](https://github.com/shap/shap/assets/71127464/cc38a70e-d138-415d-a6e3-17851fb0023c)

The `# of inhibitor kills` parameter has a much more significant effect, and there are many features with zeros. It might be that the model is underfitted. Maybe the original plots were actually made with a different model than is written?

I think the original SHAP value plots are more appealing and a better demonstration of SHAP. May I suggest tweaking the params of the XGBoost model or leaving them as defaults, to see if we can restore SHAP values that resemble the original version a bit more closely?

2023-10-03 08:26 UTC, connortann requested changes
The code cleanup looks great; however, as per my comment above, can you try to get the SHAP values looking similar to the original, perhaps by tweaking the model?

2023-10-03 08:39 UTC, connortann commented
I pushed a merge commit to fix the merge conflict, keeping the notebook as it is on this branch. The pre-commit change is no longer required as this notebook is now linted on master.

2023-10-03 14:58 UTC, connortann commented
From testing locally, it looks like these XGBoost parameters lead to a more reasonable model that have better-looking Shapley plots. May I suggest using these instead?

```python
params = {
    "objective": "binary:logistic",
    "base_score": np.mean(yt),
    "eval_metric": "logloss",
}
model = xgb.train(
    params,
    dt,
    num_boost_round=10,
    evals=[(dt, "train"), (dv, "valid")],
    early_stopping_rounds=5,
    verbose_eval=25,
)
```

This leads to a "Gold earned per min" plot like this:

![image](https://github.com/shap/shap/assets/71127464/f371fa7d-2ef7-4a8e-bb15-4a366e1786c4)

2023-10-03 15:48 UTC, CloseChoice commented
@connortann Thanks for the review and the suggested code. I reran the notebook with that and it looks way similar to the homepage version. Think this is ready for merge now

2023-10-03 16:25 UTC, connortann approved these changes
Look good, thanks again for the PR! It's great to have you on board as a contributor.

2023-10-03 16:25 UTC, merged