refactor scatter vs violin plot
shap/shap pull request #3396
Opened 2023-11-20 21:16 UTC by CloseChoice

## Overview

Closes #3036  

Description of the changes proposed in this pull request:
- fixed typos and improved descriptions.

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2023-11-29 11:27 UTC, connortann commented on notebooks/tabular_examples/tree_based_models/Scatter Density vs. Violin Plot Comparison.ipynb
> +    "These are a standard violin plot but with outliers drawn as points. This gives a more accurate representation of the density out the outliers than a kernel density estimated from only a few poin
```suggestion
    "These are a standard violin plot but with outliers drawn as points. This gives a more accurate representation of the density out the outliers than a kernel density estimated from only a few points. The color represents the average feature value at that position, so red regions high feature values dominate while blue regions low feature values dominate."
```

2023-11-29 11:28 UTC, connortann commented on notebooks/tabular_examples/tree_based_models/Scatter Density vs. Violin Plot Comparison.ipynb
> +    "The dot plot combines a scatter plot with density estimation by letting dots pile up when they don't fit. The advatange of this approach is that it does not hide anything behind kernel smoothing
```suggestion
    "The dot plot combines a scatter plot with density estimation by letting dots pile up when they don't fit. The advantage of this approach is that it does not hide anything behind kernel smoothing, so you see an exact representation of the data."
```

2023-11-29 11:31 UTC, connortann commented on notebooks/tabular_examples/tree_based_models/Scatter Density vs. Violin Plot Comparison.ipynb
> +   ],
```suggestion
   "outputs": [],
```

2023-11-29 11:33 UTC, connortann requested changes
Looks good, a few suggestions above

2023-11-29 11:34 UTC, connortann commented
I edited the PR description slightly as this will help #3036 but not fully close the issue.

2023-11-30 00:05 UTC, CloseChoice commented
Thanks @connortann for the review. I incorporated all your suggestions.

2023-11-30 00:14 UTC, connortann approved these changes
LTGM! Nice one.

2023-11-30 00:14 UTC, merged