install latest slicer commit and add test
shap/shap pull request #3560
Opened 2024-03-09 05:18 UTC by CloseChoice

## Overview

Closes #3522  

Description of the changes proposed in this pull request:
 - install latest changes from slicer
 - add failing example from issue #3522 as test

## Checklist

- [ ] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2024-03-09 11:45 UTC, connortann commented
I believe `slicer 0.0.8` is now on PyPI so we could use that?

2024-03-09 15:51 UTC, connortann commented
Looks like there is an incompatibility between `transformers` and `keras v3`:

https://github.com/huggingface/transformers/pull/28588

https://github.com/huggingface/transformers/blob/0290ec19c901adc0f1230ebdccad11c40af026f5/src/transformers/activations_tf.py#L21-L31

Maybe we need to pin the keras version to less than 2, at least for now?

2024-03-10 10:20 UTC, connortann commented on pyproject.toml
> +  'slicer @ git+https://github.com/interpretml/slicer.git@12964ec458c5169efe19df3c296fc5e3e3f6a84f',  # waiting for next release
```suggestion
  'slicer==0.08',
```

2024-03-10 18:29 UTC, connortann requested changes
Slicer has a new release on PyPi and conda forge, so we can use it directly. Great that we have a test: I definitely think for every bug fix we should include a test that fails on master but passes on the new branch.

One minor suggestion, would it be possible to simplify the test a little, whilst still reproducing the bug on #3522?

2024-03-11 08:37 UTC, CloseChoice commented
> Slicer has a new release on PyPi and conda forge, so we can use it directly. Great that we have a test: I definitely think for every bug fix we should include a test that fails on master but passes on the new branch.
> 
> One minor suggestion, would it be possible to simplify the test a little, whilst still reproducing the bug on #3522? From reading the test, I don't find it clear exactly what it is testing

Hmm, we are basically testing that we can slice a `np.array([np.array([...]), np.array([...]))` correctly. But this would actually mean that we test slicer's behaviour without the context in which it appears in shap. IMO we should test that behaviour that we fixed once is usable from now on and in this case the behaviour is just what we have in the test. Could do some minor tweaks but what we test here should be in my opinion just be that the transformer model works correctly. What are your thoughts on this? Should we explicitly test the nested np.array slicing behaviour? Or should we just create the explanation object that is the output of the model + explainer and test that it is slicable + plots work?

2024-04-05 10:11 UTC, connortann commented on pyproject.toml
> +  'slicer @ git+https://github.com/interpretml/slicer.git@12964ec458c5169efe19df3c296fc5e3e3f6a84f',  # waiting for next release
I'll go ahead and add this change, now that slicer 0.08 is out.

2024-04-05 12:26 UTC, connortann approved these changes
> we test here should be in my opinion just be that the transformer model works correctly.

Makes sense, I agree.

This LGTM - I updated the slicer pin and tests pass. Nice one

2024-04-05 12:26 UTC, merged