DOCS: Simplify standardized features docs
shap/shap pull request #3903
Opened 2024-10-31 13:23 UTC by randombenj

## Overview

Description of the changes proposed in this pull request:

Simplifies the standardized feature example a bit by not assigning the feature names manually by doing:

```python
# we add back the feature names stripped by the StandardScaler
for i, c in enumerate(X.columns):
    shap_values.feature_names[i] = c
```

But using the `transform="pandas"` option from sklearn:

```python
scaler = sklearn.preprocessing.StandardScaler().set_output(transform="pandas")
```

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] ~~Unit tests added (if fixing a bug or adding a new feature)~~

2025-03-08 19:23 UTC, CloseChoice requested changes
Sorry for the really late reply. Pls update the one thing and then we can merge on green

2025-03-08 19:23 UTC, CloseChoice commented on notebooks/tabular_examples/linear_models/Explaining a model that uses standardized features.ipynb
> +  "kernelspec": {
could you please remove this? We want the users to choose the kernel themselves.

2025-04-22 20:02 UTC, randombenj commented on notebooks/tabular_examples/linear_models/Explaining a model that uses standardized features.ipynb
> +  "kernelspec": {
Sure, I guess this was added automatically by my editor

2025-05-15 14:33 UTC, CloseChoice approved these changes
Looks good. Thanks a lot

2025-05-15 14:34 UTC, merged