Refactor color tuple creation to ensure compatibility with RGB values
shap/shap pull request #3911
Opened 2024-11-11 05:23 UTC by AndPuQing

## Overview

Closes #3895 

Description of the changes proposed in this pull request:

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [ ] Unit tests added (if fixing a bug or adding a new feature)

2024-12-02 15:57 UTC, CloseChoice commented
Could you please explain why this fixes issue #3895? 
I would also appreciate a test.

2024-12-07 10:57 UTC, AndPuQing commented
> Thanks for the PR @AndPuQing .
> 
> Was there a special case where values were wrongly set to 0 that is fixed with your function? Could you please explain why this fixes issue #3895? I would also appreciate a test, at best using the example from the issue.

---
This PR fixes a bug where `plot_text` color appears as black.  

The issue arises due to a change in the string representation of NumPy scalars introduced in NumPy 2.x. Specifically, this change affects how arrays are converted to strings. For reference, see the [NumPy 2.0 release notes](https://numpy.org/devdocs/release/2.0.0-notes.html#representation-of-numpy-scalars-changed)

### Example  

**In NumPy 2.0:**  

```python
>>> import numpy as np
>>> x = np.ones(4)
>>> tuple(x)
(np.float64(1.0), np.float64(1.0), np.float64(1.0), np.float64(1.0))
```  

In this case, the CSS color fails to take effect because the string representations are invalid, resulting in the color being displayed as black.  

**In NumPy 1.x:**  

```python
>>> import numpy as np
>>> x = np.ones(4)
>>> tuple(x)
(1.0, 1.0, 1.0, 1.0)
```  

Here, the string representations are valid, and the CSS color is applied correctly.  

### Fix  

The following code modification resolves the issue by converting NumPy arrays to Python lists using `.tolist()`, ensuring proper string representations:  

```python
def scale_color_to_255(color: tuple) -> tuple[int, int, int, float]:
    color = np.array(color).tolist() if isinstance(color[0], (np.float64, np.float32)) else color
    return tuple(int(c * 255) if i < 3 else c for i, c in enumerate(color))
```  

This ensures the string representation is valid, and the colors are displayed correctly.

2024-12-07 11:15 UTC, AndPuQing commented
And sorry, because I used black format, there are many changes in code style.

2024-12-12 05:31 UTC, CloseChoice requested changes

2024-12-12 05:31 UTC, CloseChoice commented on tests/plots/test_text.py
> +def test_color():
Would be great if you could use pytest-mpl and our test setup for plots here. Have a look at:
([baseline plots](https://github.com/shap/shap/tree/master/tests/plots/baseline), [pytest-mpl](https://www.bing.com/search?pc=MOZI&form=MOZLBR&q=pytest+mpl), [a test of ours](https://github.com/shap/shap/blob/master/tests/plots/test_beeswarm.py#L45))

2026-04-12 13:06 UTC, closed without merging