uninstall catboost for pipelines if python 3.12 is used
shap/shap pull request #3923
Opened 2024-12-03 17:27 UTC by CloseChoice

## Overview

Closes #3910 

Supports #3922
Description of the changes proposed in this pull request:

## Checklist

- [x] All [pre-commit checks](https://pre-commit.com/#install) pass.
- [x] Unit tests added (if fixing a bug or adding a new feature)

2024-12-06 16:23 UTC, CloseChoice commented
@connortann would be great to get your review on this one.

2024-12-10 18:36 UTC, connortann commented
Thanks for raising this and finding the root cause.

@CloseChoice Rather than installing and the un-installing catboost, can we instead add an appropriate dependency constraint to `pyproject.toml`?

A simple option would be to pin numpy to 1.X until catboost and ngboost fix compatibility for numpy 2. This could be done by changing this line:

https://github.com/shap/shap/blob/8954b18871d230f139ed03b1fe644f98701394a2/pyproject.toml#L89

to just:
```
"numpy<2.0"
```

Alternatively, we could avoid installing catboost and ngboost with python 3.12, by modifying pyproject.toml [line 75](https://github.com/shap/shap/blob/8954b18871d230f139ed03b1fe644f98701394a2/pyproject.toml#L73) to include the `python_version < '3.12'` spec.

I note that whatever the pins in the `"tests"` extra, we will still test against the latest numpy with the `"test-core"` job:

https://github.com/shap/shap/blob/8954b18871d230f139ed03b1fe644f98701394a2/.github/workflows/run_tests.yml#L39-L43

2024-12-10 18:36 UTC, connortann requested changes
As above, suggest implementing this change using the constraints in `pyproject.toml`

2024-12-11 09:32 UTC, connortann approved these changes
On second thoughts I'll approve this PR as it's critical to fixing the CI. @CloseChoice feel free to merge when you're happy.

2024-12-11 09:54 UTC, merged

2024-12-11 09:55 UTC, CloseChoice commented
@connortann thanks a lot. Let's create a follow-up PR to move this into pyproject.toml